### ISSUE TITLE
RFE - copy markdown link directly from a bookmark via bookmark bar OR sidebar.

### ISSUE THREAD

**Issue by geolaw** [yorkxin/copy-as-markdown#145]
Not a problem, just a suggestion. 

I use your plugin frequently, several times a day in fact. 

firefox has a "sidebars" option that gives quick access to history, bookmarks, etc ... 
it would be awesome to be able to right click on a bookmark, either from the bookmark tool bar or the sidebar and copy a markdown link of the bookmark.

Currently I have to open the bookmark and then right click "copy page link" 
It would be great to be able to just right click on either an expanded toolbar drop down or the sidebar and get the mark down link from there.

**Comment by yorkxin** [comment]
Thanks for your suggestion. This is a good idea. It seems to be possible via the [context menu's API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType) (Firefox-only though).

**Comment by yorkxin** [comment]
Hi @geolaw , glad that Copy as Markdown is helpful to you.

The Copy Bookmark as Markdown feature is now available on Firefox. Please update to version 3.0.1. Also please note that it requires additional permissions, which can be enabled from Copy as Markdown's Options page, accessible from the popup menu -> Options. 

Due to API restrictions, when you select multiple bookmarks in Bookmark Manager, and use Copy Bookmark as Markdown, there will be only one item being copied.

Also, this feature is not available on Chrome.

Please try it out and let me know your thoughts. Thanks!

**Comment by geolaw** [comment]
tested and confirmed it works as asked, thank you very much !!
